---
- name: Installer MariaDB Server
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: Activer et démarrer MariaDB
  systemd:
    name: mariadb
    enabled: yes
    state: started
